/**
 * The list of transaction sub-type options for XRP.
 * /

/**
 * @memberof module:overledger-dlt-xrp
 */

export enum TransactionXRPSubTypeOptions {
    VALUE_TRANSFER = 'VALUE_TRANSFER',
    ESCROW_CREATE = 'ESCROW_CREATE',
    ESCROW_CLAIM = 'ESCROW_CLAIM',
    ESCROW_CANCEL = 'ESCROW_CANCEL',
    TRUSTLINE_CREATE = 'TRUSTLINE_CREATE',
    ACCOUNT_SET = 'ACCOUNT_SET',
    ACCOUNT_DELETE = 'ACCOUNT_DELETE',
    CHECK_CREATE = 'CHECK_CREATE',
    CHECK_CASH = 'CHECK_CASH',
    CHECK_CANCEL = 'CHECK_CANCEL',
    DEPOSIT_PREAUTH = 'DEPOSIT_PREAUTH',
    OFFER_CREATE = 'OFFER_CREATE',
    OFFER_CANCEL = 'OFFER_CANCEL',
    PAYMENT_CHANNEL_CREATE = 'PAYMENT_CHANNEL_CREATE',
    PAYMENT_CHANNEL_FUND = 'PAYMENT_CHANNEL_FUND',
    PAYMENT_CHANNEL_CLAIM = 'PAYMENT_CHANNEL_CLAIM',
    SET_REGULAR_KEY = 'SET_REGULAR_KEY',
    SIGNER_LIST_SET = 'SIGNER_LIST_SET',
    
}

export default TransactionXRPSubTypeOptions;
