/**
 * The list of corda type options that can be used.  
 */

/**
 * @memberof module:overledger-dlt-corda
 */
// **IMPORTANT NOTE: A CHANGE HERE MAY MESS UP SMART CONTRACT INTERACTION AND THE SELECTED ENUM IS PARSED AND PREPARED BEFORE SENT TO OVERLEDGER */
export enum CordaTypeOptions { PARTY = 'PARTY', INTEGER = 'INTEGER', DOUBLE = 'DOUBLE', STRING = 'STRING', BOOLEAN = 'BOOLEAN', USER_DEFINED_CLASS = 'USER_DEFINED_CLASS', PARTY_ARRAY = 'PARTY_ARRAY', INTEGER_ARRAY = 'INTEGER_ARRAY', DOUBLE_ARRAY = 'DOUBLE_ARRAY', STRING_ARRAY = 'STRING_ARRAY', BOOLEAN_ARRAY = 'BOOLEAN_ARRAY', USER_DEFINED_CLASS_ARRAY = 'USER_DEFINED_CLASS_ARRAY',}

export default CordaTypeOptions;
